"""add total_amount, updated_at to orders and unit_price to order_products

Revision ID: 5d88e09d3843
Revises: 292d535eb676
Create Date: 2025-05-24 15:06:28.454570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d88e09d3843'
down_revision: Union[str, None] = '292d535eb676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('unit_price', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('total_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'updated_at')
    op.drop_column('order_products', 'unit_price')
    # ### end Alembic commands ###
