"""add_phone_number_to_customers

Revision ID: fd60eb75afd8
Revises: 9199bb0ac41e
Create Date: 2025-05-26 11:42:28.973931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd60eb75afd8'
down_revision: Union[str, None] = '9199bb0ac41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.drop_column('customers', 'phone_number')
    # ### end Alembic commands ###
